name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@4

      - name: Setup Go
        uses: actions/setup-go@5
        with:
          go-version: "1.25.1"

      - name: Force Failute
        run: (exit 1)
